# Generated by Django 3.1.4 on 2020-12-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_portfolio_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=60)),
                ('instrument_name', models.CharField(max_length=60)),
                ('number_of_shares', models.IntegerField()),
                ('trade_date', models.DateField()),
                ('close_out_date', models.DateField()),
                ('buy_price', models.FloatField()),
                ('sell_price', models.FloatField()),
                ('net_earnings', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
